= Apache Camel UI
// Variables:
:current-release: v001
:ui-module-name: antora-ui-camel
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/apache/camel-website
:img-ci-status: {url-project}/badges/master/pipeline.svg
// External URLs:
:url-camel: https://camel.apache.org/
:url-antora: https://antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-node: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-yarn: https://yarnpkg.com

This project represents the Apache Camel UI theme that is used in the {url-camel}[Apache Camel website] documentation site.
The website is generated with {url-antora}[Antora] and this is the UI theme for that.

== Use the Camel UI

If you want to use this UI theme in your Antora-generated site, add the following UI configuration to your playbook:

[source,yaml,subs=attributes+]
----
ui:
  bundle:
    url: {url-project}/releases/download/{current-release}/ui-bundle.zip
    snapshot: true
----

Read on to learn how to use your own build of the this UI theme.

== Quickstart

This section offers a basic tutorial for learning how to preview the UI and bundle it for use with Antora.

=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-node}[Node] (command: `node`)
* {url-gulp}[Gulp CLI] (command: `gulp`)
* {url-yarn}[Yarn] (command: `yarn`)

==== git

First, make sure you have git installed.

 $ git --version

If not, {url-git-dl}[download and install] the git package for your system.

==== Node

Next, make sure that you have Node.js (herein "`Node`") installed.

 $ node --version

If this command fails with an error, you don't have Node installed.
If the command doesn't report a Node LTS version (e.g., v10.14.2), you don't have a suitable version of Node installed.

While you can install Node from the official packages, we strongly recommend that you use {url-nvm}[nvm]
(Node Version Manager) to install and manage Node.
Follow the {url-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node 10 using the following command:

 $ nvm install 10

You can switch to this version of Node at any time using the following command:

 $ nvm use 10

To make Node 10 the default in new terminals, type:

 $ nvm alias default 10

Now that you have Node 10 installed, you can proceed with installing the Gulp CLI and Yarn.

==== Gulp CLI

Next, you'll need the Gulp command-line interface (CLI).
This package provides the `gulp` command which executes the version of Gulp declared by the project.

You should install the Gulp CLI globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g gulp-cli

==== Yarn

Finally, you'll need Yarn, which is the preferred package manager for the Node ecosystem.

You should install Yarn globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g yarn

Now that you have the prerequisites installed, you can fetch and build the Apache Camel UI project.

=== Clone and Initialize the UI Project

Clone the Camel UI project using git:

[subs=attributes+]
 $ git clone {url-project} &&
   cd camel-website/{ui-module-name}

The command above clones the Apache Camel Website project and then switches to the UI project folder on your filesystem.
Stay in this project folder in order to initialize the project using Yarn.

Use Yarn to install the project's dependencies.
In your terminal, execute the following command (while inside the `{ui-module-name} project folder):

 $ yarn install

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle.

=== Preview the UI

The default UI project is configured to preview offline.
That's what the files in the [.path]_preview-site-src/_ folder are for.
This folder contains HTML file fragments that provide a representative sample of content from the site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ yarn preview

You'll see a URL listed in the output of this command:

....
[12:59:28] Starting 'preview:serve'...
[12:59:28] Starting server...
[12:59:28] Server started http://localhost:5252
[12:59:28] Running server
....

Navigate to that URL to view the preview site.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending
the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to bundle the UI in order to preview the UI on the real site in local development, run the following command:

 $ yarn build

The UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can then point Antora at this bundle using the `--ui-bundle-url` command-line option.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ gulp bundle:pack

== Copyright and License

=== Software

The software in this repository (build scripts, JavaScript files, Handlebars templates, foundation CSS, utility icons, etc)
is part of the {url-antora}[Antora project] and therefore copyright for these parts and the underlying source code belongs
to {url-opendevise}[OpenDevise Inc] and the {url-antora}[Antora project].

As such, use of the software is granted under the terms of the
https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0). See link:LICENSE[] to find the full license text.

