approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

plugins:
  - path: github-release-binary.js

yarnPath: .yarn/releases/yarn-4.18.0.cjs
