site:
  title: Apache Camel
  url: https://camel.apache.org/
  start_page: manual::index.adoc

content:
  sources:
    - url: https://gitbox.apache.org/repos/asf/camel.git
      branches: master
      start_path: docs/user-manual
    - url: https://gitbox.apache.org/repos/asf/camel.git
      branches: master
      start_path: docs/components
    - url: git@github.com:apache/camel-k.git
      branches: antora
      start_path: docs

ui:
  bundle:
    url: ./antora-ui-camel/build/ui-bundle.zip

asciidoc:
  attributes:
    product-name: 'Apache Camel'

urls:
  redirect_facility: disabled

output:
  dir: ./static
