loggingLevel=info
loggingColor=false
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.download=true
camel.jbang.fresh=false
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.mcp=false
camel.jbang.openapiUi=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.22.0
camel.jbang.springBootVersion=4.1.0
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusVersion=3.38.2
camel.jbang.quarkusExtensionRegistryBaseUri=https\://registry.quarkus.io
camel.jbang.javaVersion=21
camel.jbang.kameletsVersion=4.21.0
camel.main.name=timer-log
camel.main.routesIncludePattern=file\:timer-log.yaml
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.22.0
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.21.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.22.0
dependency=mvn\:org.apache.camel\:camel-timer\:4.22.0
